# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

class ViewCityWeather(object):



    def setupUi(self, MainWindow, data):

        self.weather_layout_background = QtWidgets.QLabel(MainWindow)
        self.weather_layout_background.setGeometry(QtCore.QRect(30, 200, 841, 261))
        self.weather_layout_background.setStyleSheet("background-color: rgb(0, 0, 127)")
        self.weather_layout_background.setText("")
        self.weather_layout_background.setObjectName("weather_layout_background")

        self.day1_pic = QtWidgets.QLabel(MainWindow)
        self.day1_pic.setGeometry(QtCore.QRect(40, 210, 101, 81))
        self.day1_pic.setText("")
        self.day1_pic.setScaledContents(True)
        self.day1_pic.setObjectName("day1_pic")

        self.temperature1 = QtWidgets.QLabel(MainWindow)
        self.temperature1.setGeometry(QtCore.QRect(40, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature1.setFont(font)
        self.temperature1.setStyleSheet("color: rgb(255, 103, 118)")
        self.temperature1.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature1.setObjectName("temperature1")

        self.humidity1 = QtWidgets.QLabel(MainWindow)
        self.humidity1.setGeometry(QtCore.QRect(40, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humidity1.setFont(font)
        self.humidity1.setStyleSheet("color: rgb(142, 172, 255)")
        self.humidity1.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity1.setObjectName("humidity1")

        self.wind1 = QtWidgets.QLabel(MainWindow)
        self.wind1.setGeometry(QtCore.QRect(40, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wind1.setFont(font)
        self.wind1.setStyleSheet("color: rgb(247, 255, 211)")
        self.wind1.setAlignment(QtCore.Qt.AlignCenter)
        self.wind1.setObjectName("wind1")

        self.date1 = QtWidgets.QLabel(MainWindow)
        self.date1.setGeometry(QtCore.QRect(40, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date1.setFont(font)
        self.date1.setStyleSheet("color: rgb(43, 255, 78)")
        self.date1.setAlignment(QtCore.Qt.AlignCenter)
        self.date1.setObjectName("date1")

        self.wind2 = QtWidgets.QLabel(MainWindow)
        self.wind2.setGeometry(QtCore.QRect(160, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wind2.setFont(font)
        self.wind2.setStyleSheet("color: rgb(247, 255, 211)")
        self.wind2.setAlignment(QtCore.Qt.AlignCenter)
        self.wind2.setObjectName("wind2")

        self.day2_pic = QtWidgets.QLabel(MainWindow)
        self.day2_pic.setGeometry(QtCore.QRect(160, 210, 101, 81))
        self.day2_pic.setText("")
        self.day2_pic.setScaledContents(True)
        self.day2_pic.setObjectName("day2_pic")

        self.temperature2 = QtWidgets.QLabel(MainWindow)
        self.temperature2.setGeometry(QtCore.QRect(160, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature2.setFont(font)
        self.temperature2.setStyleSheet("color: rgb(255, 103, 118)")
        self.temperature2.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature2.setObjectName("temperature2")

        self.date2 = QtWidgets.QLabel(MainWindow)
        self.date2.setGeometry(QtCore.QRect(160, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date2.setFont(font)
        self.date2.setStyleSheet("color: rgb(43, 255, 78)")
        self.date2.setAlignment(QtCore.Qt.AlignCenter)
        self.date2.setObjectName("date2")

        self.humidity2 = QtWidgets.QLabel(MainWindow)
        self.humidity2.setGeometry(QtCore.QRect(160, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humidity2.setFont(font)
        self.humidity2.setStyleSheet("color: rgb(142, 172, 255)")
        self.humidity2.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity2.setObjectName("humidity2")

        self.wind3 = QtWidgets.QLabel(MainWindow)
        self.wind3.setGeometry(QtCore.QRect(280, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wind3.setFont(font)
        self.wind3.setStyleSheet("color: rgb(247, 255, 211)")
        self.wind3.setAlignment(QtCore.Qt.AlignCenter)
        self.wind3.setObjectName("wind3")

        self.day3_pic = QtWidgets.QLabel(MainWindow)
        self.day3_pic.setGeometry(QtCore.QRect(280, 210, 101, 81))
        self.day3_pic.setText("")
        self.day3_pic.setScaledContents(True)
        self.day3_pic.setObjectName("day3_pic")

        self.temperature3 = QtWidgets.QLabel(MainWindow)
        self.temperature3.setGeometry(QtCore.QRect(280, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature3.setFont(font)
        self.temperature3.setStyleSheet("color: rgb(255, 103, 118)")
        self.temperature3.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature3.setObjectName("temperature3")

        self.date3 = QtWidgets.QLabel(MainWindow)
        self.date3.setGeometry(QtCore.QRect(280, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date3.setFont(font)
        self.date3.setStyleSheet("color: rgb(43, 255, 78)")
        self.date3.setAlignment(QtCore.Qt.AlignCenter)
        self.date3.setObjectName("date3")

        self.humidity3 = QtWidgets.QLabel(MainWindow)
        self.humidity3.setGeometry(QtCore.QRect(280, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humidity3.setFont(font)
        self.humidity3.setStyleSheet("color: rgb(142, 172, 255)")
        self.humidity3.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity3.setObjectName("humidity3")

        self.wind4 = QtWidgets.QLabel(MainWindow)
        self.wind4.setGeometry(QtCore.QRect(400, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wind4.setFont(font)
        self.wind4.setStyleSheet("color: rgb(247, 255, 211)")
        self.wind4.setAlignment(QtCore.Qt.AlignCenter)
        self.wind4.setObjectName("wind4")

        self.day4_pic = QtWidgets.QLabel(MainWindow)
        self.day4_pic.setGeometry(QtCore.QRect(400, 210, 101, 81))
        self.day4_pic.setText("")
        self.day4_pic.setScaledContents(True)
        self.day4_pic.setObjectName("day4_pic")

        self.temperature4 = QtWidgets.QLabel(MainWindow)
        self.temperature4.setGeometry(QtCore.QRect(400, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature4.setFont(font)
        self.temperature4.setStyleSheet("color: rgb(255, 103, 118)")
        self.temperature4.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature4.setObjectName("temperature4")

        self.date4 = QtWidgets.QLabel(MainWindow)
        self.date4.setGeometry(QtCore.QRect(400, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date4.setFont(font)
        self.date4.setStyleSheet("color: rgb(43, 255, 78)")
        self.date4.setAlignment(QtCore.Qt.AlignCenter)
        self.date4.setObjectName("date4")

        self.humidity4 = QtWidgets.QLabel(MainWindow)
        self.humidity4.setGeometry(QtCore.QRect(400, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humidity4.setFont(font)
        self.humidity4.setStyleSheet("color: rgb(142, 172, 255)")
        self.humidity4.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity4.setObjectName("humidity4")

        self.day5_pic = QtWidgets.QLabel(MainWindow)
        self.day5_pic.setGeometry(QtCore.QRect(520, 210, 101, 81))
        self.day5_pic.setText("")
        self.day5_pic.setScaledContents(True)
        self.day5_pic.setObjectName("day5_pic")

        self.wind5 = QtWidgets.QLabel(MainWindow)
        self.wind5.setGeometry(QtCore.QRect(520, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wind5.setFont(font)
        self.wind5.setStyleSheet("color: rgb(247, 255, 211)")
        self.wind5.setAlignment(QtCore.Qt.AlignCenter)
        self.wind5.setObjectName("wind5")

        self.date5 = QtWidgets.QLabel(MainWindow)
        self.date5.setGeometry(QtCore.QRect(520, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date5.setFont(font)
        self.date5.setStyleSheet("color: rgb(43, 255, 78)")
        self.date5.setAlignment(QtCore.Qt.AlignCenter)
        self.date5.setObjectName("date5")

        self.humidity5 = QtWidgets.QLabel(MainWindow)
        self.humidity5.setGeometry(QtCore.QRect(520, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humidity5.setFont(font)
        self.humidity5.setStyleSheet("color: rgb(142, 172, 255)")
        self.humidity5.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity5.setObjectName("humidity5")

        self.temperature5 = QtWidgets.QLabel(MainWindow)
        self.temperature5.setGeometry(QtCore.QRect(520, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature5.setFont(font)
        self.temperature5.setStyleSheet("color: rgb(255, 103, 118)")
        self.temperature5.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature5.setObjectName("temperature5")

        self.wind6 = QtWidgets.QLabel(MainWindow)
        self.wind6.setGeometry(QtCore.QRect(640, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wind6.setFont(font)
        self.wind6.setStyleSheet("color: rgb(247, 255, 211)")
        self.wind6.setAlignment(QtCore.Qt.AlignCenter)
        self.wind6.setObjectName("wind6")

        self.humidity6 = QtWidgets.QLabel(MainWindow)
        self.humidity6.setGeometry(QtCore.QRect(640, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humidity6.setFont(font)
        self.humidity6.setStyleSheet("color: rgb(142, 172, 255)")
        self.humidity6.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity6.setObjectName("humidity6")

        self.date6 = QtWidgets.QLabel(MainWindow)
        self.date6.setGeometry(QtCore.QRect(640, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date6.setFont(font)
        self.date6.setStyleSheet("color: rgb(43, 255, 78)")
        self.date6.setAlignment(QtCore.Qt.AlignCenter)
        self.date6.setObjectName("date6")

        self.day6_pic = QtWidgets.QLabel(MainWindow)
        self.day6_pic.setGeometry(QtCore.QRect(640, 210, 101, 81))
        self.day6_pic.setText("")
        self.day6_pic.setScaledContents(True)
        self.day6_pic.setObjectName("day6_pic")

        self.temperature6 = QtWidgets.QLabel(MainWindow)
        self.temperature6.setGeometry(QtCore.QRect(640, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature6.setFont(font)
        self.temperature6.setStyleSheet("color: rgb(255, 103, 118)")
        self.temperature6.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature6.setObjectName("temperature6")

        self.wind7 = QtWidgets.QLabel(MainWindow)
        self.wind7.setGeometry(QtCore.QRect(760, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.wind7.setFont(font)
        self.wind7.setStyleSheet("color: rgb(247, 255, 211)")
        self.wind7.setAlignment(QtCore.Qt.AlignCenter)
        self.wind7.setObjectName("wind7")
        self.humidity7 = QtWidgets.QLabel(MainWindow)
        self.humidity7.setGeometry(QtCore.QRect(760, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.humidity7.setFont(font)
        self.humidity7.setStyleSheet("color: rgb(142, 172, 255)")
        self.humidity7.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity7.setObjectName("humidity7")

        self.date7 = QtWidgets.QLabel(MainWindow)
        self.date7.setGeometry(QtCore.QRect(760, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.date7.setFont(font)
        self.date7.setStyleSheet("color: rgb(43, 255, 78)")
        self.date7.setAlignment(QtCore.Qt.AlignCenter)
        self.date7.setObjectName("date7")

        self.day7_pic = QtWidgets.QLabel(MainWindow)
        self.day7_pic.setGeometry(QtCore.QRect(760, 210, 101, 81))
        self.day7_pic.setText("")
        self.day7_pic.setScaledContents(True)
        self.day7_pic.setObjectName("day7_pic")

        self.temperature7 = QtWidgets.QLabel(MainWindow)
        self.temperature7.setGeometry(QtCore.QRect(760, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temperature7.setFont(font)
        self.temperature7.setStyleSheet("color: rgb(255, 103, 118)")
        self.temperature7.setAlignment(QtCore.Qt.AlignCenter)
        self.temperature7.setObjectName("temperature7")

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.updateForecast(data)
        self.showWidgets()

    def showWidgets(self):
        self.weather_layout_background.show()
        self.day1_pic.show()
        self.day2_pic.show()
        self.day3_pic.show()
        self.day4_pic.show()
        self.day5_pic.show()
        self.day6_pic.show()
        self.day7_pic.show()
        self.temperature1.show()
        self.temperature2.show()
        self.temperature3.show()
        self.temperature4.show()
        self.temperature5.show()
        self.temperature6.show()
        self.temperature7.show()
        self.humidity1.show()
        self.humidity2.show()
        self.humidity3.show()
        self.humidity4.show()
        self.humidity5.show()
        self.humidity6.show()
        self.humidity7.show()
        self.date1.show()
        self.date2.show()
        self.date3.show()
        self.date4.show()
        self.date5.show()
        self.date6.show()
        self.date7.show()

    def updateForecast(self, data):

        weather = ["Sunny", "Cloudy", "Sunny + Cloudy", "Rainy", "Stormy", "Lightning"]
        weatherPic = ["Sunny.png", "Cloudy.png", "SunnyCloudy.png", "Rainy.png", "Stormy.png", "Lightning.png"]
        dataPic = []
        del data[0]
        listkeys = list(data.key())
        listvals = list(data.values())
        for item in listvals:
            for i in range(7):
                for j in range(6):
                    if item[i][0] == weather[j]:
                        dataPic.append(weatherPic[j])
        
        _translate = QtCore.QCoreApplication.translate

        self.day1_pic.setPixmap(QtGui.QPixmap("pic/" + dataPic[0]))
        self.temperature1.setText(_translate("MainWindow", str(listvals[0][1]) + chr(176) + "C"))
        self.wind1.setText(_translate("MainWindow", "Wind: " + str(listvals[0][2])))
        self.humidity1.setText(_translate("MainWindow", "Humid: " + str(listvals[0][3])))
        self.date1.setText(_translate("MainWindow", listkeys[0]))

        self.day2_pic.setPixmap(QtGui.QPixmap("pic/" + dataPic[1]))
        self.temperature2.setText(_translate("MainWindow", str(listvals[1][1]) + chr(176) + "C"))
        self.wind2.setText(_translate("MainWindow", "Wind: " + str(listvals[1][2])))
        self.humidity2.setText(_translate("MainWindow", "Humid: " + str(listvals[1][3])))
        self.date2.setText(_translate("MainWindow", listkeys[1]))

        self.day3_pic.setPixmap(QtGui.QPixmap("pic/" + dataPic[2]))
        self.temperature3.setText(_translate("MainWindow", str(listvals[2][1]) + chr(176) + "C"))
        self.wind3.setText(_translate("MainWindow", "Wind: " + str(listvals[2][2])))
        self.humidity3.setText(_translate("MainWindow", "Humid: " + str(listvals[2][3])))
        self.date3.setText(_translate("MainWindow", listkeys[2]))

        self.day4_pic.setPixmap(QtGui.QPixmap("pic/" + dataPic[3]))
        self.temperature4.setText(_translate("MainWindow", str(listvals[3][1]) + chr(176) + "C"))
        self.wind4.setText(_translate("MainWindow", "Wind: " + str(listvals[3][2])))
        self.humidity4.setText(_translate("MainWindow", "Humid: " + str(listvals[3][3])))
        self.date4.setText(_translate("MainWindow", listkeys[3]))

        self.day5_pic.setPixmap(QtGui.QPixmap("pic/" + dataPic[4]))
        self.temperature5.setText(_translate("MainWindow", str(listvals[4][1]) + chr(176) + "C"))
        self.wind5.setText(_translate("MainWindow", "Wind: " + str(listvals[4][2])))
        self.humidity5.setText(_translate("MainWindow", "Humid: " + str(listvals[4][3])))
        self.date5.setText(_translate("MainWindow", listkeys[4]))

        self.day6_pic.setPixmap(QtGui.QPixmap("pic/" + dataPic[5]))
        self.temperature6.setText(_translate("MainWindow", str(listvals[5][1]) + chr(176) + "C"))
        self.wind6.setText(_translate("MainWindow", "Wind: " + str(listvals[5][2])))
        self.humidity6.setText(_translate("MainWindow", "Humid: " + str(listvals[5][3])))
        self.date6.setText(_translate("MainWindow", listkeys[5]))

        self.day7_pic.setPixmap(QtGui.QPixmap("pic/" + dataPic[6]))
        self.temperature7.setText(_translate("MainWindow", str(listvals[6][1]) + chr(176) + "C"))
        self.wind7.setText(_translate("MainWindow", "Wind: " + str(listvals[6][2])))
        self.humidity7.setText(_translate("MainWindow", "Humid: " + str(listvals[6][3])))
        self.date7.setText(_translate("MainWindow", listkeys[6]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = ViewCityWeather()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())